//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 12:43:27 PM CET 
//


package allapis.springbootsoap.com;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="etudiantInfo" type="{http://com.springbootsoap.allapis}etudiantInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "etudiantInfo"
})
@XmlRootElement(name = "addEtudiantRequest")
public class AddEtudiantRequest {

    @XmlElement(required = true)
    protected EtudiantInfo etudiantInfo;

    /**
     * Gets the value of the etudiantInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EtudiantInfo }
     *     
     */
    public EtudiantInfo getEtudiantInfo() {
        return etudiantInfo;
    }

    /**
     * Sets the value of the etudiantInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EtudiantInfo }
     *     
     */
    public void setEtudiantInfo(EtudiantInfo value) {
        this.etudiantInfo = value;
    }

}
