//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 12:43:27 PM CET 
//


package allapis.springbootsoap.com;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the allapis.springbootsoap.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: allapis.springbootsoap.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateEtudiantResponse }
     * 
     */
    public UpdateEtudiantResponse createUpdateEtudiantResponse() {
        return new UpdateEtudiantResponse();
    }

    /**
     * Create an instance of {@link DeleteEtudiantResponse }
     * 
     */
    public DeleteEtudiantResponse createDeleteEtudiantResponse() {
        return new DeleteEtudiantResponse();
    }

    /**
     * Create an instance of {@link EtudiantInfo }
     * 
     */
    public EtudiantInfo createEtudiantInfo() {
        return new EtudiantInfo();
    }

    /**
     * Create an instance of {@link DeleteEtudiantRequest }
     * 
     */
    public DeleteEtudiantRequest createDeleteEtudiantRequest() {
        return new DeleteEtudiantRequest();
    }

    /**
     * Create an instance of {@link GetEtudiantResponse }
     * 
     */
    public GetEtudiantResponse createGetEtudiantResponse() {
        return new GetEtudiantResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetEtudiantByIdRequest }
     * 
     */
    public GetEtudiantByIdRequest createGetEtudiantByIdRequest() {
        return new GetEtudiantByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateEtudiantRequest }
     * 
     */
    public UpdateEtudiantRequest createUpdateEtudiantRequest() {
        return new UpdateEtudiantRequest();
    }

    /**
     * Create an instance of {@link AddEtudiantRequest }
     * 
     */
    public AddEtudiantRequest createAddEtudiantRequest() {
        return new AddEtudiantRequest();
    }

    /**
     * Create an instance of {@link AddEtudiantResponse }
     * 
     */
    public AddEtudiantResponse createAddEtudiantResponse() {
        return new AddEtudiantResponse();
    }

}
